export default {
  check: (url: string) => url.replace("//", "/"),
  EXTERNAL_DAKDAKA: "/dakdata",
  EXTERNAL_ACTIVITIETEN: "/", // link on portal configuration
  HOME: "/so",
  LOGIN: "/login",
  LOGOUT: "/login/logout",
  NEW_ACCOUNT: "/login/new-account",
  ACCOUNT_REQUEST: "/login/account-request",
  SO_LIST: "/so/list",
  SO_PROMOTED: "/so/list/promoted",
  SC_HOME: "/so/cs",
  SO_DETAILS: "/so/list/details",
  SO_DOCUMENT: "/document-file",
  FORGOT: "/login/forgot",
  RESET_PASSWORD: "/login/reset-password",
  TERMS_OF_USE: "/terms-of-use",
  PRIVACY_STATEMENT: "/privacy-statement",
  DISCLAIMER: "/disclaimer",
  CREATE_SERVICE_ORDER: "/create-service-order",
  SEARCH_CLIENT: "/search-client",
  CREATE_WORK_ORDER: "/create-work-order",
  CONFIRM_MODAL: "/confirm",
  PLANNING: "/so/planning",
  SC_LIST: "/so/sc/list",
  INDEXEREN: "/so/sc/indexeren",
  LOG_MOMENT: "/so/list/moments",
  MOMENT_HISTORY: "/moment-history"
};
