import Colors from "dakota-portal/dist/components/Colors";

export const APPOINTMENTS_TYPES = {
  NO_APPOINTMENT: "NO_APPOINTMENT",
  NOT_PLANNED: "NOT_PLANNED",
  SCHEDULED: "SCHEDULED",
  DONE: "DONE"
};

export const APPOINTMENTS_TITLES = {
  [APPOINTMENTS_TYPES.NO_APPOINTMENT]: "Geen Afspraak",
  [APPOINTMENTS_TYPES.NOT_PLANNED]: "Afspraak Niet geplaned",
  [APPOINTMENTS_TYPES.SCHEDULED]: "Afspraak Gepland",
  [APPOINTMENTS_TYPES.DONE]: "Afspraak Gereed"
};

export const APPOINTMENTS_COLORS = {
  [APPOINTMENTS_TYPES.NO_APPOINTMENT]: Colors.lightGray,
  [APPOINTMENTS_TYPES.NOT_PLANNED]: Colors.orangePeel,
  [APPOINTMENTS_TYPES.SCHEDULED]: Colors.royalBlue,
  [APPOINTMENTS_TYPES.DONE]: Colors.mediumSeaGreen
};

export const APPOINTMENTS_STATUSES = {
  No_Appointment: APPOINTMENTS_TYPES.NO_APPOINTMENT,
  Not_Planned: APPOINTMENTS_TYPES.NOT_PLANNED,
  Scheduled: APPOINTMENTS_TYPES.SCHEDULED,
  Done: APPOINTMENTS_TYPES.DONE
};

export const APPOINTMENTS_STATUSES_BY_TITLES = {
  "Geen Afspraak": "No_Appointment",
  "Afspraak Niet geplaned": "Not_Planned",
  "Afspraak Gepland": "Scheduled",
  "Afspraak Gereed": "Done"
};
// Contracts
export const CONTRACTS_TYPES = {
  MAINTENANCE_SCHEDULED: "MAINTENANCE_SCHEDULED",
  APPOINTMENT_SCHEDULED: "APPOINTMENT_SCHEDULED",
  MAINTENANCE_PROPOSAL: "MAINTENANCE_PROPOSAL",
  MAINTENANCE_GREED: "MAINTENANCE_GREED"
};

export const CONTRACTS_TITLES = {
  [CONTRACTS_TYPES.MAINTENANCE_SCHEDULED]: "Onderhoud Geplaned",
  [CONTRACTS_TYPES.APPOINTMENT_SCHEDULED]: "Afspraak Gepland",
  [CONTRACTS_TYPES.MAINTENANCE_PROPOSAL]: "Onderhoud Voorstel",
  [CONTRACTS_TYPES.MAINTENANCE_GREED]: "Onderhoud Greed"
};

export const CONTRACTS_COLORS = {
  [CONTRACTS_TYPES.MAINTENANCE_SCHEDULED]: Colors.mediumSeaGreen,
  [CONTRACTS_TYPES.APPOINTMENT_SCHEDULED]: Colors.lightningYellow,
  [CONTRACTS_TYPES.MAINTENANCE_PROPOSAL]: Colors.cinnabar,
  [CONTRACTS_TYPES.MAINTENANCE_GREED]: Colors.lynch
};

export const CONTRACTS_STATUSES = {
  Invoicing_Allowed: CONTRACTS_TYPES.MAINTENANCE_SCHEDULED,
  Offered: CONTRACTS_TYPES.MAINTENANCE_PROPOSAL,
  Order: CONTRACTS_TYPES.APPOINTMENT_SCHEDULED,
  Expired: CONTRACTS_TYPES.MAINTENANCE_GREED
};

export const CONTRACTS_STATUSES_BY_TITLES = {
  [CONTRACTS_TITLES.MAINTENANCE_SCHEDULED]: "Invoicing_Allowed",
  [CONTRACTS_TITLES.MAINTENANCE_PROPOSAL]: "Offered",
  [CONTRACTS_TITLES.APPOINTMENT_SCHEDULED]: "Order",
  [CONTRACTS_TITLES.MAINTENANCE_GREED]: "Expired"
};
